Vaihtoehtoinen toteutus mm. get-cards -funktiolle. remove-card -funkt…
hollannikas/texas-host pull request #1
Opened 2017-02-21 12:54 UTC by he1kki

…io ei poista valittua korttia pakasta.

2017-02-21 17:35 UTC, hollannikas commented
Added your test and a test for get-card in [this commit](https://github.com/hollannikas/texas-host/commit/4e3683bb74df3a93158325fad31ceb334b685bee)

That exposed a bug in my `deal-cards`, which I fixed in master in [this commit](https://github.com/hollannikas/texas-host/commit/4a8a0f7c4abbbe5259016e25990416a0ef45168c)

2017-02-21 17:40 UTC, hollannikas commented
I'm not sure how you plan to keep track of the cards you have already dealt from the deck in your version of deal-cards.

2017-02-22 06:33 UTC, hollannikas requested changes

2017-02-22 06:33 UTC, hollannikas commented on src/texas_host/core.clj
> +    (let [[cards-before deck-before] (deal-cards (- amount 1) deck)]
How do you intend to keep track of the cards dealt here?

2017-02-22 06:33 UTC, hollannikas commented on src/texas_host/core.clj
I would suggest keeping the (British English) term pack; that way the diff is clearer.

> A complete set of cards is called a pack (UK English), deck (US English) -  [Wikipedia](https://en.wikipedia.org/wiki/Playing_card)

2017-02-22 06:33 UTC, hollannikas commented on src/texas_host/core.clj
> +  (println (str "John got the following cards " (deal-hand "bert"))))
What have you got against John? Again, this is unnecessary and clutters the diff :)

2017-02-22 06:33 UTC, hollannikas commented on src/texas_host/core.clj
> +        (println "deck-after " card-chosen deck-after)
Why did you choose to get the card and then remove the card over calling a function that does both? It seems like an excessive use of `let`

2017-02-22 07:48 UTC, he1kki commented on src/texas_host/core.clj
> +        (println "deck-after " card-chosen deck-after)
Good question. I guess because my it was defined as such in my original algorithm. I'll change it back.

2017-02-22 07:49 UTC, he1kki commented on src/texas_host/core.clj
> +  (println (str "John got the following cards " (deal-hand "bert"))))
:) It was a mishap. It probably was the first thing I changed in the code a way back.

2017-02-22 07:57 UTC, he1kki commented on src/texas_host/core.clj
> +    (let [[cards-before deck-before] (deal-cards (- amount 1) deck)]
While amount is greater than zero, deal-cards function is called recursively. When amount is zero, an empty vector is returned. In the previous function call a new card is chosen and added to the cards dealt. And so on and so on until the cards dealt are returned from the first deal-cards function call.

2017-02-22 08:01 UTC, he1kki commented on src/texas_host/core.clj
Oh, I didn't know that. I've been watching too many American movies I guess.

2017-02-22 08:55 UTC, closed without merging